server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: reservation
          uri: http://localhost:8081
          predicates:
            - Path=/reservations/** 
        - id: vaccinemgmt
          uri: http://localhost:8082
          predicates:
            - Path=/vaccineMgmts/** 
        - id: mypage
          uri: http://localhost:8083
          predicates:
            - Path= /myPages/**
        - id: approval
          uri: http://localhost:8084
          predicates:
            - Path=/approvals/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: reservation
          uri: http://reservation:8080
          predicates:
            - Path=/reservations/** 
        - id: vaccinemgmt
          uri: http://vaccinemgmt:8080
          predicates:
            - Path=/vaccineMgmts/** 
        - id: mypage
          uri: http://mypage:8080
          predicates:
            - Path= /myPages/**
        - id: approval
          uri: http://approval:8080
          predicates:
            - Path=/approvals/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080