apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaccinemgmt
  labels:
    app: vaccinemgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaccinemgmt
  template:
    metadata:
      labels:
        app: vaccinemgmt
    spec:
      containers:
        - name: vaccinemgmt
          image: username/vaccinemgmt:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5